from __future__ import annotations

from typing import Any

from twn_toolkit.profiles import (
    DNSProfileStore,
    NTPHostProfileStore,
    PingProfileStore,
    PortScanProfileStore,
    RadiusProfileStore,
    SNMPCredentialProfileStore,
    SNMPHostProfileStore,
    SNMPOidProfileStore,
    TracerouteHostProfileStore,
)
from twn_toolkit.tool_catalog import ToolLink, ToolRegistry


def backup_items(instance_path: str) -> list[dict[str, Any]]:
    return [
        {
            "id": "ping_profiles",
            "label": "Ping profiles",
            "description": "Saved ping target lists.",
            "store": PingProfileStore(instance_path),
            "sensitive": False,
        },
        {
            "id": "dns_host_profiles",
            "label": "DNS host profiles",
            "description": "Saved DNS hostname/query lists.",
            "store": DNSProfileStore(instance_path, "hosts"),
            "sensitive": False,
        },
        {
            "id": "dns_server_profiles",
            "label": "DNS server profiles",
            "description": "Saved DNS server lists.",
            "store": DNSProfileStore(instance_path, "servers"),
            "sensitive": False,
        },
        {
            "id": "radius_server_profiles",
            "label": "RADIUS server profiles",
            "description": "Saved RADIUS servers and shared secrets.",
            "store": RadiusProfileStore(instance_path, "servers"),
            "sensitive": True,
        },
        {
            "id": "radius_credential_profiles",
            "label": "RADIUS credential profiles",
            "description": "Saved RADIUS test usernames and passwords.",
            "store": RadiusProfileStore(instance_path, "credentials"),
            "sensitive": True,
        },
        {
            "id": "radius_attribute_profiles",
            "label": "RADIUS request-attribute profiles",
            "description": "Saved request-attribute sets.",
            "store": RadiusProfileStore(instance_path, "attributes"),
            "sensitive": False,
        },
        {
            "id": "snmp_credential_profiles",
            "label": "SNMP credential profiles",
            "description": "Saved SNMP communities, usernames, auth keys, and privacy keys.",
            "store": SNMPCredentialProfileStore(instance_path),
            "sensitive": True,
        },
        {
            "id": "snmp_host_profiles",
            "label": "SNMP host profiles",
            "description": "Saved SNMP target hosts.",
            "store": SNMPHostProfileStore(instance_path),
            "sensitive": False,
        },
        {
            "id": "snmp_oid_profiles",
            "label": "SNMP OID profiles",
            "description": "Saved SNMP OID lists.",
            "store": SNMPOidProfileStore(instance_path),
            "sensitive": False,
        },
        {
            "id": "port_scan_host_profiles",
            "label": "TCP scanner host profiles",
            "description": "Saved TCP scanner host lists.",
            "store": PortScanProfileStore(instance_path, "hosts"),
            "sensitive": False,
        },
        {
            "id": "port_scan_port_profiles",
            "label": "TCP scanner port profiles",
            "description": "Saved TCP scanner port lists.",
            "store": PortScanProfileStore(instance_path, "ports"),
            "sensitive": False,
        },
        {
            "id": "ntp_host_profiles",
            "label": "NTP host profiles",
            "description": "Saved NTP target lists.",
            "store": NTPHostProfileStore(instance_path),
            "sensitive": False,
        },
        {
            "id": "traceroute_host_profiles",
            "label": "Traceroute host profiles",
            "description": "Saved traceroute target lists.",
            "store": TracerouteHostProfileStore(instance_path),
            "sensitive": False,
        },
    ]


def register_tools(registry: ToolRegistry) -> None:
    registry.add_tools(
        [
            ToolLink(
                "tools.whats_my_ip",
                "What’s My IP?",
                "See the client address used to connect to this toolkit server.",
                "tools.whats_my_ip",
                "network",
                "Network Tools",
            ),
            ToolLink(
                "tools.subnet_excluder",
                "Subnet Excluder",
                "Subtract CIDR networks from one or more parent networks.",
                "tools.subnet_excluder",
                "network",
                "Network Tools",
            ),
            ToolLink(
                "tools.ping",
                "Multi-Host Ping",
                "Troubleshoot reachability, latency, and packet loss across multiple hosts.",
                "tools.ping_tool",
                "network",
                "Network Tools",
            ),
            ToolLink(
                "tools.multi_ssh",
                "Multi-SSH",
                "Run the same command sequence across multiple SSH hosts.",
                "tools.multi_ssh",
                "network",
                "Network Tools",
                risk="advanced",
            ),
            ToolLink(
                "tools.dns_response",
                "DNS Lookup Tester",
                "Compare DNS answers and lookup latency across multiple resolvers.",
                "tools.dns_response",
                "network",
                "Network Tools",
            ),
            ToolLink(
                "tools.radius_test",
                "RADIUS Authentication Test",
                "Compare PAP, CHAP, PEAP/MSCHAPv2, or EAP-TLS authentication across RADIUS servers.",
                "tools.radius_test",
                "network",
                "Network Tools",
                risk="advanced",
            ),
            ToolLink(
                "tools.speed_test",
                "Wi-Fi / LAN Speed Test",
                "Measure browser-to-toolkit latency, jitter, download, and upload on the local network.",
                "tools.speed_test",
                "network",
                "Network Tools",
            ),
            ToolLink(
                "tools.certificate_inspector",
                "Certificate Chain Inspector",
                "Inspect the exact TLS chain a web server presents and validate trust and hostnames.",
                "tools.certificate_inspector",
                "network",
                "Network Tools",
            ),
            ToolLink(
                "tools.snmp_test",
                "SNMP Tester",
                "Validate SNMPv2c and SNMPv3 access with reusable devices, credentials, and OID collections.",
                "tools.snmp_test",
                "network",
                "Network Tools",
            ),
            ToolLink(
                "tools.port_scanner",
                "TCP Port Scanner",
                "Check selected TCP ports across multiple authorized hosts.",
                "tools.port_scanner",
                "network",
                "Network Tools",
                risk="advanced",
            ),
            ToolLink(
                "tools.ntp_test",
                "NTP Tester",
                "Measure clock offset, response delay, jitter, and synchronization health.",
                "tools.ntp_test",
                "network",
                "Network Tools",
            ),
            ToolLink(
                "tools.dhcp_discover",
                "DHCP Discover",
                "Send a Discover and inspect Offers without requesting a lease.",
                "tools.dhcp_discover",
                "network",
                "Network Tools",
                risk="advanced",
            ),
            ToolLink(
                "tools.packet_replay",
                "Packet Replay",
                "Preview, modify, and transmit raw Ethernet frames.",
                "tools.packet_replay",
                "network",
                "Network Tools",
                risk="high",
            ),
            ToolLink(
                "tools.path_mtu",
                "Path MTU Tester",
                "Find the largest unfragmented packet that reaches a destination.",
                "tools.path_mtu",
                "network",
                "Network Tools",
            ),
            ToolLink(
                "tools.api_request",
                "Webhook / API Tester",
                "Send a bounded HTTP request and inspect status, timing, headers, and body.",
                "tools.api_request",
                "network",
                "Network Tools",
            ),
            ToolLink(
                "tools.syslog_receiver",
                "Syslog Tools",
                "Generate test messages or listen briefly for UDP and TCP syslog traffic.",
                "tools.syslog_receiver",
                "network",
                "Network Tools",
            ),
            ToolLink(
                "tools.traceroute",
                "Traceroute",
                "Trace up to 10 destinations with live graphical hops and text output.",
                "tools.traceroute",
                "network",
                "Network Tools",
            ),
        ]
    )
    registry.map_endpoints(
        {
            "tools.dhcp_discover": "tools.dhcp_discover",
            "tools.packet_replay": "tools.packet_replay",
            "tools.path_mtu": "tools.path_mtu",
            "tools.api_request": "tools.api_request",
            "tools.syslog_receiver": "tools.syslog_receiver",
            "tools.whats_my_ip": "tools.whats_my_ip",
            "tools.server_public_ip": "tools.whats_my_ip",
            "tools.ntp_test": "tools.ntp_test",
            "tools.save_ntp_profile": "tools.ntp_test",
            "tools.delete_ntp_profile": "tools.ntp_test",
            "tools.traceroute": "tools.traceroute",
            "tools.save_traceroute_profile": "tools.traceroute",
            "tools.delete_traceroute_profile": "tools.traceroute",
            "tools.traceroute_run": "tools.traceroute",
            "tools.port_scanner": "tools.port_scanner",
            "tools.save_port_scan_profile": "tools.port_scanner",
            "tools.delete_port_scan_profile": "tools.port_scanner",
            "tools.snmp_test": "tools.snmp_test",
            "tools.save_snmp_profile": "tools.snmp_test",
            "tools.delete_snmp_profile": "tools.snmp_test",
            "tools.certificate_inspector": "tools.certificate_inspector",
            "tools.speed_test": "tools.speed_test",
            "tools.speed_test_ping": "tools.speed_test",
            "tools.speed_test_download": "tools.speed_test",
            "tools.speed_test_upload": "tools.speed_test",
            "tools.speed_test_activity": "tools.speed_test",
            "tools.subnet_excluder": "tools.subnet_excluder",
            "tools.ping_tool": "tools.ping",
            "tools.ping_run": "tools.ping",
            "tools.ping_validate_targets": "tools.ping",
            "tools.ping_activity": "tools.ping",
            "tools.save_ping_profile": "tools.ping",
            "tools.delete_ping_profile": "tools.ping",
            "tools.dns_response": "tools.dns_response",
            "tools.save_dns_profile": "tools.dns_response",
            "tools.delete_dns_profile": "tools.dns_response",
            "tools.radius_test": "tools.radius_test",
            "tools.save_radius_profile": "tools.radius_test",
            "tools.delete_radius_profile": "tools.radius_test",
            "tools.multi_ssh": "tools.multi_ssh",
        }
    )
