from __future__ import annotations

from typing import Any

from twn_toolkit.profiles import (
    DNSProfileStore,
    NTPHostProfileStore,
    PingProfileStore,
    PortScanProfileStore,
    RadiusProfileStore,
    SNMPCredentialProfileStore,
    SNMPHostProfileStore,
    SNMPOidProfileStore,
    TracerouteHostProfileStore,
    WOLTargetProfileStore,
)
from twn_toolkit.tool_catalog import ToolLink, ToolRegistry
from twn_toolkit.ssh_commandlets import SSHCommandletStore


def backup_items(instance_path: str) -> list[dict[str, Any]]:
    return [
        {
            "id": "ping_profiles",
            "label": "Ping profiles",
            "description": "Saved ping target lists.",
            "store": PingProfileStore(instance_path),
            "sensitive": False,
        },
        {
            "id": "dns_host_profiles",
            "label": "DNS host profiles",
            "description": "Saved DNS hostname/query lists.",
            "store": DNSProfileStore(instance_path, "hosts"),
            "sensitive": False,
        },
        {
            "id": "dns_server_profiles",
            "label": "DNS server profiles",
            "description": "Saved DNS server lists.",
            "store": DNSProfileStore(instance_path, "servers"),
            "sensitive": False,
        },
        {
            "id": "radius_server_profiles",
            "label": "RADIUS server profiles",
            "description": "Saved RADIUS servers and shared secrets.",
            "store": RadiusProfileStore(instance_path, "servers"),
            "sensitive": True,
        },
        {
            "id": "radius_credential_profiles",
            "label": "RADIUS credential profiles",
            "description": "Saved RADIUS test usernames and passwords.",
            "store": RadiusProfileStore(instance_path, "credentials"),
            "sensitive": True,
        },
        {
            "id": "radius_attribute_profiles",
            "label": "RADIUS request-attribute profiles",
            "description": "Saved request-attribute sets.",
            "store": RadiusProfileStore(instance_path, "attributes"),
            "sensitive": False,
        },
        {
            "id": "snmp_credential_profiles",
            "label": "SNMP credential profiles",
            "description": "Saved SNMP communities, usernames, auth keys, and privacy keys.",
            "store": SNMPCredentialProfileStore(instance_path),
            "sensitive": True,
        },
        {
            "id": "snmp_host_profiles",
            "label": "SNMP host profiles",
            "description": "Saved SNMP target hosts.",
            "store": SNMPHostProfileStore(instance_path),
            "sensitive": False,
        },
        {
            "id": "snmp_oid_profiles",
            "label": "SNMP OID profiles",
            "description": "Saved SNMP OID lists.",
            "store": SNMPOidProfileStore(instance_path),
            "sensitive": False,
        },
        {
            "id": "port_scan_host_profiles",
            "label": "TCP scanner host profiles",
            "description": "Saved TCP scanner host lists.",
            "store": PortScanProfileStore(instance_path, "hosts"),
            "sensitive": False,
        },
        {
            "id": "port_scan_port_profiles",
            "label": "TCP scanner port profiles",
            "description": "Saved TCP scanner port lists.",
            "store": PortScanProfileStore(instance_path, "ports"),
            "sensitive": False,
        },
        {
            "id": "ntp_host_profiles",
            "label": "NTP host profiles",
            "description": "Saved NTP target lists.",
            "store": NTPHostProfileStore(instance_path),
            "sensitive": False,
        },
        {
            "id": "traceroute_host_profiles",
            "label": "Traceroute host profiles",
            "description": "Saved traceroute target lists.",
            "store": TracerouteHostProfileStore(instance_path),
            "sensitive": False,
        },
        {
            "id": "wol_target_profiles",
            "label": "Wake-on-LAN device groups",
            "description": "Saved device names, MAC addresses, and optional verification hosts.",
            "store": WOLTargetProfileStore(instance_path),
            "sensitive": False,
        },
        {
            "id": "ssh_commandlets",
            "label": "SSH Commandlets",
            "description": "Saved Multi-SSH command templates, optional target matrices, and metadata.",
            "store": SSHCommandletStore(instance_path),
            "sensitive": True,
        },
    ]


def register_tools(registry: ToolRegistry) -> None:
    registry.add_tools(
        [
            ToolLink(
                "tools.whats_my_ip",
                "What’s My IP?",
                "See the client address used to connect to this toolkit server.",
                "tools.whats_my_ip",
                "network",
                "Network Tools",
                nav_icon="◎",
                nav_group="addressing",
            ),
            ToolLink(
                "tools.subnet_excluder",
                "Subnet Excluder",
                "Subtract CIDR networks from one or more parent networks.",
                "tools.subnet_excluder",
                "network",
                "Network Tools",
                nav_icon="⌗",
                nav_group="addressing",
            ),
            ToolLink(
                "tools.ping",
                "Multi-Host Ping",
                "Troubleshoot reachability, latency, and packet loss across multiple hosts.",
                "tools.ping_tool",
                "network",
                "Network Tools",
                nav_icon="↔",
                nav_group="multi-host",
            ),
            ToolLink(
                "tools.multi_ssh",
                "Multi-SSH",
                "Run shared or variable-aware Commandlets across multiple SSH hosts.",
                "tools.multi_ssh",
                "network",
                "Network Tools",
                risk="advanced",
                nav_icon="⌘",
                nav_group="multi-host",
            ),
            ToolLink(
                "tools.multi_sftp",
                "Multi-Transfer",
                "Fetch files from multiple hosts over SFTP or SCP into the datastore or a one-shot ZIP.",
                "tools.multi_transfer",
                "network",
                "Network Tools",
                risk="advanced",
                nav_icon="⇄",
                nav_group="multi-host",
            ),
            ToolLink(
                "tools.dns_response",
                "DNS Tester",
                "Compare DNS answers and latency or run a controlled resolver load test.",
                "tools.dns_response",
                "network",
                "Network Tools",
                nav_icon="Aa",
                nav_group="addressing",
            ),
            ToolLink(
                "tools.radius_test",
                "RADIUS Authentication Test",
                "Compare PAP, CHAP, PEAP/MSCHAPv2, or EAP-TLS authentication across RADIUS servers.",
                "tools.radius_test",
                "network",
                "Network Tools",
                risk="advanced",
                nav_icon="◉",
                nav_group="services",
            ),
            ToolLink(
                "tools.speed_test",
                "Wi-Fi / LAN Speed Test",
                "Measure browser-to-toolkit latency, jitter, download, and upload on the local network.",
                "tools.speed_test",
                "network",
                "Network Tools",
                nav_icon="≋",
                nav_group="traffic",
            ),
            ToolLink(
                "tools.iperf3",
                "iPerf3 Tester",
                "Run an authorized client test or manage a multi-test iPerf3 server.",
                "tools.iperf3",
                "network",
                "Network Tools",
                risk="advanced",
                nav_icon="⇆",
                nav_group="traffic",
            ),
            ToolLink(
                "tools.multicast",
                "Multicast Tester",
                "Join, inspect, generate, and measure IPv4 multicast streams across selected interfaces.",
                "tools.multicast",
                "network",
                "Network Tools",
                risk="advanced",
                nav_icon="◌",
                nav_group="traffic",
            ),
            ToolLink(
                "tools.certificate_inspector",
                "Certificate Chain Inspector",
                "Inspect the exact TLS chain a web server presents and validate trust and hostnames.",
                "tools.certificate_inspector",
                "network",
                "Network Tools",
                nav_icon="✓",
                nav_group="services",
            ),
            ToolLink(
                "tools.certificate_automation",
                "Certificate Automation",
                "Guide Let's Encrypt DNS validation or enroll, protect, rotate, and export certificates through internal Microsoft AD CS profiles (Beta).",
                "tools.certificate_automation",
                "network",
                "Network Tools",
                risk="advanced",
                nav_icon="◇",
                nav_group="services",
            ),
            ToolLink(
                "tools.snmp_test",
                "SNMP Tester",
                "Validate SNMPv2c and SNMPv3 access with reusable devices, credentials, and OID collections.",
                "tools.snmp_test",
                "network",
                "Network Tools",
                nav_icon="≣",
                nav_group="services",
            ),
            ToolLink(
                "tools.port_scanner",
                "TCP Port Scanner",
                "Check selected TCP ports across multiple authorized hosts.",
                "tools.port_scanner",
                "network",
                "Network Tools",
                risk="advanced",
                nav_icon="#",
                nav_group="multi-host",
            ),
            ToolLink(
                "tools.ntp_test",
                "NTP Tester",
                "Measure clock offset, response delay, jitter, and synchronization health.",
                "tools.ntp_test",
                "network",
                "Network Tools",
                nav_icon="◷",
                nav_group="addressing",
            ),
            ToolLink(
                "tools.dhcp_discover",
                "DHCP Discover",
                "Send a Discover and inspect Offers without requesting a lease.",
                "tools.dhcp_discover",
                "network",
                "Network Tools",
                risk="advanced",
                nav_icon="⇣",
                nav_group="traffic",
            ),
            ToolLink(
                "tools.wake_on_lan",
                "Wake-on-LAN",
                "Wake local or routed devices with bounded magic packets and optional ping verification.",
                "tools.wake_on_lan",
                "network",
                "Network Tools",
                risk="advanced",
                nav_icon="⏻",
                nav_group="services",
            ),
            ToolLink(
                "tools.packet_capture",
                "Packet Capture",
                "Capture bounded PCAP files from a local or SPAN-connected interface.",
                "tools.packet_capture",
                "network",
                "Network Tools",
                risk="high",
                nav_icon="●",
                nav_group="traffic",
            ),
            ToolLink(
                "tools.packet_replay",
                "Packet Replay",
                "Preview, modify, and transmit raw Ethernet frames.",
                "tools.packet_replay",
                "network",
                "Network Tools",
                risk="high",
                nav_icon="▶",
                nav_group="traffic",
            ),
            ToolLink(
                "tools.path_mtu",
                "Path MTU Tester",
                "Find the largest unfragmented packet that reaches a destination.",
                "tools.path_mtu",
                "network",
                "Network Tools",
                nav_icon="↕",
                nav_group="addressing",
            ),
            ToolLink(
                "tools.api_request",
                "Webhook / API Tester",
                "Send a bounded HTTP request and inspect status, timing, headers, and body.",
                "tools.api_request",
                "network",
                "Network Tools",
                nav_icon="{}",
                nav_group="services",
            ),
            ToolLink(
                "tools.syslog_receiver",
                "Syslog Tools",
                "Generate test messages or listen briefly for UDP and TCP syslog traffic.",
                "tools.syslog_receiver",
                "network",
                "Network Tools",
                nav_icon="≡",
                nav_group="services",
            ),
            ToolLink(
                "tools.traceroute",
                "Traceroute",
                "Trace up to 10 destinations with live graphical hops and text output.",
                "tools.traceroute",
                "network",
                "Network Tools",
                nav_icon="⌁",
                nav_group="addressing",
            ),
        ]
    )
    registry.map_endpoints(
        {
            "tools.packet_capture": "tools.packet_capture",
            "tools.start_packet_capture": "tools.packet_capture",
            "tools.packet_capture_status": "tools.packet_capture",
            "tools.inspect_captured_packets": "tools.packet_capture",
            "tools.stop_packet_capture": "tools.packet_capture",
            "tools.download_packet_capture": "tools.packet_capture",
            "tools.save_packet_capture": "tools.packet_capture",
            "tools.delete_packet_capture": "tools.packet_capture",
            "tools.dhcp_discover": "tools.dhcp_discover",
            "tools.packet_replay": "tools.packet_replay",
            "tools.path_mtu": "tools.path_mtu",
            "tools.api_request": "tools.api_request",
            "tools.syslog_receiver": "tools.syslog_receiver",
            "tools.whats_my_ip": "tools.whats_my_ip",
            "tools.server_public_ip": "tools.whats_my_ip",
            "tools.record_ip_snapshot": "tools.whats_my_ip",
            "tools.ntp_test": "tools.ntp_test",
            "tools.save_ntp_profile": "tools.ntp_test",
            "tools.duplicate_ntp_profile": "tools.ntp_test",
            "tools.delete_ntp_profile": "tools.ntp_test",
            "tools.traceroute": "tools.traceroute",
            "tools.save_traceroute_profile": "tools.traceroute",
            "tools.duplicate_traceroute_profile": "tools.traceroute",
            "tools.delete_traceroute_profile": "tools.traceroute",
            "tools.traceroute_run": "tools.traceroute",
            "tools.wake_on_lan": "tools.wake_on_lan",
            "tools.save_wol_profile": "tools.wake_on_lan",
            "tools.duplicate_wol_profile": "tools.wake_on_lan",
            "tools.delete_wol_profile": "tools.wake_on_lan",
            "tools.port_scanner": "tools.port_scanner",
            "tools.save_port_scan_profile": "tools.port_scanner",
            "tools.duplicate_port_scan_profile": "tools.port_scanner",
            "tools.delete_port_scan_profile": "tools.port_scanner",
            "tools.snmp_test": "tools.snmp_test",
            "tools.save_snmp_profile": "tools.snmp_test",
            "tools.duplicate_snmp_profile": "tools.snmp_test",
            "tools.delete_snmp_profile": "tools.snmp_test",
            "tools.snmp_interfaces": "tools.snmp_test",
            "tools.snmp_interface_sample": "tools.snmp_test",
            "tools.snmp_interface_samples": "tools.snmp_test",
            "tools.start_snmp_interface_monitor": "tools.snmp_test",
            "tools.snmp_interface_monitor_session": "tools.snmp_test",
            "tools.snmp_interface_monitor_session_samples": "tools.snmp_test",
            "tools.update_snmp_interface_monitor_session": "tools.snmp_test",
            "tools.certificate_inspector": "tools.certificate_inspector",
            "tools.certificate_automation": "tools.certificate_automation",
            "tools.start_acme_dns_request": "tools.certificate_automation",
            "tools.acme_dns_request_status": "tools.certificate_automation",
            "tools.check_acme_dns_request": "tools.certificate_automation",
            "tools.continue_acme_dns_request": "tools.certificate_automation",
            "tools.cancel_acme_dns_request": "tools.certificate_automation",
            "tools.download_acme_dns_certificate": "tools.certificate_automation",
            "tools.save_pki_credential": "tools.certificate_automation",
            "tools.duplicate_pki_credential": "tools.certificate_automation",
            "tools.delete_pki_credential": "tools.certificate_automation",
            "tools.save_pki_server": "tools.certificate_automation",
            "tools.duplicate_pki_server": "tools.certificate_automation",
            "tools.delete_pki_server": "tools.certificate_automation",
            "tools.test_pki_server": "tools.certificate_automation",
            "tools.save_pki_template": "tools.certificate_automation",
            "tools.duplicate_pki_template": "tools.certificate_automation",
            "tools.delete_pki_template": "tools.certificate_automation",
            "tools.enroll_managed_certificate": "tools.certificate_automation",
            "tools.collect_pending_certificate": "tools.certificate_automation",
            "tools.download_managed_certificate": "tools.certificate_automation",
            "tools.delete_managed_certificate": "tools.certificate_automation",
            "tools.speed_test": "tools.speed_test",
            "tools.speed_test_ping": "tools.speed_test",
            "tools.speed_test_download": "tools.speed_test",
            "tools.speed_test_upload": "tools.speed_test",
            "tools.speed_test_activity": "tools.speed_test",
            "tools.iperf3": "tools.iperf3",
            "tools.multicast": "tools.multicast",
            "tools.multicast_live": "tools.multicast",
            "tools.start_iperf3_server": "tools.iperf3",
            "tools.stop_iperf3_server": "tools.iperf3",
            "tools.iperf3_server_status": "tools.iperf3",
            "tools.clear_iperf3_server_results": "tools.iperf3",
            "tools.subnet_excluder": "tools.subnet_excluder",
            "tools.ping_tool": "tools.ping",
            "tools.ping_run": "tools.ping",
            "tools.ping_validate_targets": "tools.ping",
            "tools.ping_activity": "tools.ping",
            "tools.start_ping_session": "tools.ping",
            "tools.ping_session": "tools.ping",
            "tools.ping_session_samples": "tools.ping",
            "tools.update_ping_session_targets": "tools.ping",
            "tools.save_ping_profile": "tools.ping",
            "tools.duplicate_ping_profile": "tools.ping",
            "tools.delete_ping_profile": "tools.ping",
            "tools.dns_response": "tools.dns_response",
            "tools.save_dns_profile": "tools.dns_response",
            "tools.duplicate_dns_profile": "tools.dns_response",
            "tools.delete_dns_profile": "tools.dns_response",
            "tools.radius_test": "tools.radius_test",
            "tools.save_radius_profile": "tools.radius_test",
            "tools.duplicate_radius_profile": "tools.radius_test",
            "tools.delete_radius_profile": "tools.radius_test",
            "tools.multi_ssh": "tools.multi_ssh",
            "tools.import_ssh_hosts": "tools.multi_ssh",
            "tools.delete_ssh_commandlet": "tools.multi_ssh",
            "tools.multi_transfer": "tools.multi_sftp",
            "tools.multi_sftp": "tools.multi_sftp",
        }
    )
